server.port=8082

spring.datasource.url=jdbc:h2:mem:dataviewer;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.servlet.multipart.max-file-size=10240MB
spring.servlet.multipart.max-request-size=10240MB
server.tomcat.max-http-form-post-size=-1
